# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Chemistry-Canonicalize
version:      0.11
version_from: Canonicalize.pm
installdirs:  site
requires:
    Chemistry::Mol:                0.24
    Math::BigInt:                  

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
